db_tier: db-f1-micro
minReplicas: '1'
maxReplicas: '1'
app: syfosoknadbrukernotifikasjon
namespace: flex
team: flex
kafkaPool: nav-dev
externalHosts:
  - kafka-schema-registry.nais-q.adeo.no
env:
  SYKEPENGESOKNAD_FRONTEND_URL: https://www-gcp.dev.nav.no/syk/sykepengesoknad/soknader/
