db_tier: db-f1-micro
cpu: 50m
memory: 640Mi
minReplicas: 1
maxReplicas: 1
kafkaPool: nav-dev
env:
  SYKEPENGESOKNAD_FRONTEND_URL: https://www.ekstern.dev.nav.no/syk/sykepengesoknad/soknader/
  SPRING_PROFILES_ACTIVE: default,testdatareset
