apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosoknadbrukernotifikasjon
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  strategy:
    type: Recreate
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 60
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        tier: {{db_tier}}
        diskAutoresize: true
        databases:
          - name: syfosoknadbrukernotifikasjon-db
  accessPolicy:
    outbound:
      external:
      {{#each externalHosts as |url|}}
         - host: {{url}}
      {{/each}}
  kafka:
    pool: {{kafkaPool}}
  leaderElection: true
  env:
  {{#each env}}
     - name: {{@key}}
       value: {{this}}
  {{/each}}
