db_tier: db-custom-1-3840
cpu: 100m
memory: 640Mi
minReplicas: 1
maxReplicas: 1
kafkaPool: nav-prod
env:
  SYKEPENGESOKNAD_FRONTEND_URL: https://www.nav.no/syk/sykepengesoknad/soknader/
  SPRING_PROFILES_ACTIVE: default
