minReplicas: '1'
maxReplicas: '1'
app: syfosoknadbrukernotifikasjon
namespace: flex
team: flex
kafkaPool: nav-prod
externalHosts:
  - kafka-schema-registry.nais.adeo.no
env:
  SYKEPENGESOKNAD_FRONTEND_URL: https://www.nav.no/syk/sykepengesoknad/soknader/
