server:
  port: 8080

spring:
  main.banner-mode: 'off'
  profiles:
    active: default
  flyway:
    enabled: true
  datasource:
    url: "jdbc:postgresql://${NAIS_DATABASE_SYFOSOKNADBRUKERNOTIFIKASJON_SYFOSOKNADBRUKERNOTIFIKASJON_DB_HOST}:${NAIS_DATABASE_SYFOSOKNADBRUKERNOTIFIKASJON_SYFOSOKNADBRUKERNOTIFIKASJON_DB_PORT}/${NAIS_DATABASE_SYFOSOKNADBRUKERNOTIFIKASJON_SYFOSOKNADBRUKERNOTIFIKASJON_DB_DATABASE}"
    username: ${NAIS_DATABASE_SYFOSOKNADBRUKERNOTIFIKASJON_SYFOSOKNADBRUKERNOTIFIKASJON_DB_USERNAME}
    password: ${NAIS_DATABASE_SYFOSOKNADBRUKERNOTIFIKASJON_SYFOSOKNADBRUKERNOTIFIKASJON_DB_PASSWORD}


on-prem-kafka:
  schema-registry-url: ${KAFKA_SCHEMA_REGISTRY_URL}
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_URL}
  security-protocol: SASL_SSL
  username: ${SERVICEUSER_USERNAME}
  password: ${SERVICEUSER_PASSWORD}

aiven-kafka:
  auto-offset-reset: none
  security-protocol: SSL


frontend-url: ${SYKEPENGESOKNAD_FRONTEND_URL}

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: health,prometheus
    path-mapping.prometheus: /prometheus

logging.config: "classpath:logback.xml"

