ALTER TABLE BRUKERNOTIFIKASJON
    ADD COLUMN UTSENDELSESTIDSPUNKT TIMESTAMP WITH TIME ZONE NULL,
    ADD COLUMN SOKNADSTYPE          VARCHAR(36)              NULL,
    ADD COLUMN EKSTERNT_VARSEL      BOOLEAN                  NOT NULL DEFAULT FALSE,
    ALTER COLUMN OPPGAVE_SENDT DROP NOT NULL;


